imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

nelmio_alice:
    locale: 'es_ES'  # Generar valores para español del España con Faker Generator
    seed: 1          # Valor usado para asegurar que se generan los mismos resultados aleatorios
                     # poner a null para desactivar
    loading_limit: 5 # Alice puede necesitar usar recursividad para obtener ciertos valores
                     # Este parámetro pone una cota máxima a la recursividad, parando si se alcanza
    max_unique_values_retry: 150 # Número máximo de intentos para que Alice genere un valor
                                 # único antes de parar y dar un mensaje de error

#swiftmailer:
#    delivery_addresses: ['me@example.com']
