# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        base_de_datos:
            entity:
                class: AppBundle\Entity\Usuario
                property: nombreUsuario

    encoders:
        AppBundle\Entity\Usuario: plaintext

    role_hierarchy:
      ROLE_SECRETARIO: ['ROLE_DOCENTE', 'ROLE_GESTOR_PRESTAMOS']
      ROLE_DOCENTE: 'ROLE_USER'
      ROLE_GESTOR_PRESTAMOS: 'ROLE_USER'
      ROLE_ORDENANZA: ['ROLE_USER', 'ROLE_GESTOR_PRESTAMOS']

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            #anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
